### PR TITLE
Feature/ios27 support

### PR DESCRIPTION
**Pull request by zqxwce**
This is a DRAFT, not ready to be merged.
But as usual, if someone wants to try it out, who am I to stop them? :)

at any case, currently this works with iOS27b3 + cloudOS26.4.
some functionality may also be broken, was not able to fully test everything yet.

GLHF

### CODE REVIEW

File: scripts/cfw_install.sh [hunk 1]
```diff
@@ -507,6 +512,22 @@ cp -R "$TEMP_DIR/launchd.plist" "$MNT1/System/Library/xpc/launchd.plist"
...
+# and falls back to temporary-sandbox → boots (wallpaper broken). With port 25 claimed,
+# the kernel SENDS the synchronous upcall and blocks for a reply, but 27's
+# containermanagerd does not implement the 26.4 kernel's upcall protocol and never
+# replies → early-boot thread deadlocks → SpringBoard never comes up. Verified by
+# controlled boots (2026-07-15): pristine 27 cache connects in ~10 vphoned retries;
+# adding {HostSpecialPort:25} hangs at 100+ retries and never connects. The correct fix
+# must be kernel-side (handle the absent/failed upcall without temporary-sandbox) or in
+# per-app container resolution — NOT a launchd-cache edit. See
+# research/0_binary_patch_comparison.md for the full writeup.
+
```
Comment (zqxwce) [inline scripts/cfw_install.sh]: remove this documentation here, this is not the place for random documentation

File: sources/FirmwarePatcher/Kernel/KernelJBPatcher.swift [hunk 2]
```diff
@@ -49,6 +56,51 @@ public final class KernelJBPatcher: KernelJBPatcherBase, Patcher {
...
+        // iOS 27 deleted the kernel-side containermanagerd upcall (no HOST_CONTAINERD_PORT
+        // / CM_KERN_* in the stock 27 kernel), so on the 26.4 kernel the upcall fails for
+        // every 27 platform app → they are autoboxed into `temporary-sandbox`, which denies
+        // backboard.display.services → Campo (wallpaper) crash-loops, + intelligencetasksd/
+        // feedbackd. Flip the `cbz w0,<success>` guard to `b <success>` so a failed upcall
+        // takes the success path instead of autobox/kill. No-op-in-effect for version-matched
+        // userlands (there the upcall succeeds, so cbz already branches to <success>).
+        patchContainerManagerUpcall()
+
+        // DISABLED (kept off): patchParavirtDisplayPrimary was a wrong theory —
```
Comment (zqxwce) [inline sources/FirmwarePatcher/Kernel/KernelJBPatcher.swift]: remove this if the code is disabled, also remove all dead code related

File: README.md [hunk 3]
```diff
@@ -20,6 +20,7 @@ Boot a virtual iPhone (iOS 26) via Apple's Virtualization.framework using PCC re
 | Mac16,11 26.2   | `17,3_26.4_23E246`    | `26.4-23E5207q` |
 | Mac16,11 26.2   | `17,3_26.5_23F77`     | `26.4-23E5207q` |
 | Mac16,11 27.0b2 | `17,3_26.5.2_23F84`   | `26.4-23E5207q` |
+| Mac16,11 27.0b2 | `17,3_27.0_24A5380h`  | `26.4-23E5207q` |
 
 iOS <= 26.0.1 use the 26.1 PCC vphone600 stack plus the CFW-time `IOMobileFramebuffer` SwapEnd payload-size patch.
```
Comment (zqxwce) [inline README.md:25]: Missing iOS 27.x
